project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  elsevier-pdf:
    journal:
      name: Journal Name
      formatting: preprint
      model: 3p
      layout: onecolumn
      cite-style: number
  docx: default
  jats: default



